os: linux
sudo: false
language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - master

matrix:
  allow_failures:
    - go: master

notifications:
  email:
    on_success: change
    on_failure: always

script: make
