# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        go:
          - "1.19.13"
          - "stable"
        arch:
          - "amd64"
          - "arm64"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      env:
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -v ./...
        make server

    - name: Test
      run: |
        make vet
        go test -v ./...
